meta_product_name: "Bijouterie Abraham"
meta_title: "Bijouterie Abraham - Offering the highest quality of service"
meta_description: "Bijouterie Abraham is an independent family owned jewelery store with over 40 years' experience and expertise."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards